---
title: "Cohort State-Transition Models in R: A Tutorial - Part I"
subtitle: "Appendix"
author: 
  - Fernando Alarid-Escudero, PhD^[Division of Public Administration, Center for Research and Teaching in Economics (CIDE), Aguascalientes, AGS, Mexico]
  - Eline Krijkamp, MSc^[Department of Epidemiology and Department of Radiology, Erasmus University Medical Center, Rotterdam, The Netherlands]
  - Eva A. Enns, PhD^[Division of Health Policy and Management, University of Minnesota School of Public Health, Minneapolis, MN, USA]
  - Alan Yang, MSc^[The Hospital for Sick Children, Toronto]
  - Myriam G.M. Hunink, PhD$^\dagger$^[Center for Health Decision Sciences, Harvard T.H. Chan School of Public Health, Boston, USA]
  - Petros Pechlivanoglou, PhD^[The Hospital for Sick Children, Toronto and University of Toronto, Toronto, Ontario, Canada]
  - Hawre Jalal, MD, PhD^[University of Pittsburgh, Pittsburgh, PA, USA]
date: '`r Sys.Date()`'
output: pdf_document
classoption: landscape
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Cohort tutorial model components
### Table I
This table contains an overview of the key model components used in the code for the Sick-Sicker example from the [DARTH](http://darthworkgroup.com/publications/) manuscript: “An Introductory Tutorial to Cohort State-Transition Models in R”. The first column gives the mathematical notation for some of the model components that are used in the equations in the manuscript. The second column gives a description of the model component with the R name in the third column. The forth gives the data structure, e.g. scalar, list, vector, matrix etc, with the according dimensions of this data structure in the fifth column. The final column indicated the type of data that is stored in the data structure, e.g. numeric (5.2,6.3,7.4), category (A,B,C), integer (5,6,7), logical (TRUE, FALSE).


| Element | Description                           | R name        | Data structure | Dimensions        | Data type   |
|--------|----------------------------------------|--------------|-------------|---------------------|---------|
| $n_t$        | Time horizon                     | `n_t`        | scalar          |                   | numeric     |
| $v_s$        | Names of the health states       | `v_n`        | vector          | `n_states` x 1    | character   |
| $n_s$        | Number of health states          | `n_states`   | scalar          |                   | numeric     |
| $v_{str}$    | Names of the strategies          | `v_names_str`| scalar          |                   | character   |
| $n_{str}$    | Number of strategies             | `n_str`      | scalar          |                   | character   |
| \(\mathbf{d_c}\)  | Discount rate for costs     | `d_c`        | scalar          |                   | numeric     |
| \(\mathbf{d_e}\)  | Discount rate for effects   | `d_e`        | scalar          |                   | numeric     |
|              | Discount weights for costs       | `v_dwc`      | vector          | (`n_t` x 1 ) + 1  | numeric     | 
|              | Discount weights for effects     | `v_dwe`      | vector          | (`n_t` x 1 ) + 1  | numeric     | 
|\(\mathbf{wcc}\) | Within-cycle correction weights using Simpson's 1/3 rule    | `v_wcc`  | vector    | (`n_t` x 1 ) + 1  | numeric     |
| $age_{_0}$   | Age at baseline                  | `n_age_init` | scalar          |                   | numeric     |
| $age$        | Maximum age of follow up         | `n_age_max`  | scalar          |                   | numeric     |
| \(M\)        | Cohort trace                     | `m_M`        | matrix          | (`n_t` + 1) x `n_states`    | numeric     |
| \(m_0\)      | Initial state vector             | `v_s_init`   | vector          | 1 x `n_states`         | numeric     |
| \(m_t\)      | State vector in cycle t          | `v_mt`       | vector          | 1 x `n_states`         | numeric     |
|              |                                  |              |                 |                   |             |
|       |  **Transition probabilities**           |              |                 |                   |             |  
| $p_{[H,S1]}$  | From Healthy to Sick conditional on surviving  | `p_HS1`      | scalar          |                   | numeric     |
| $p_{[S1,H]}$  | From Sick to Healthy conditional on surviving  | `p_S1H`      | scalar          |                   | numeric     |
| $p_{[S1,S2]}$ | From Sick to Sicker conditional on surviving   | `p_S1S2`     | scalar          |                   | numeric     |
| $r_{[H,D]}$   | Constant rate of dying when Healthy (all-cause mortality rate)| `r_HD`       | scalar          |                   | numeric     |
| $hr_{[S1,H]}$ | Hazard ratio of death in Sick vs Healthy       | `hr_S1`       | scalar          |                   | numeric     |
| $hr_{[S2,H]}$ | Hazard ratio of death in Sicker vs Healthy     | `hr_S2`       | scalar          |                   | numeric     |
| $hr_{[S1,S2]_{trtB}}$ | Hazard ratio of becoming Sicker when Sick under treatment B    | `hr_S1S2_trtB`| scalar   |  | numeric     |
| \(P\)         | Time-independent transition probability matrix  | `m_P`  | matrix | `n_states` x `n_states`    | numeric     |
|               |                                |               |                 |                   |           |
|        | **Annual costs**                      |               |                 |                   |           |
|              | Healthy individuals             | `c_H`         | scalar          |                   | numeric   |
|              | Sick individuals in Sick        | `c_S1`        | scalar          |                   | numeric   |
|              | Sick individuals in Sicker      | `c_S2`        | scalar          |                   | numeric   |
|              | Dead individuals                | `c_D`         | scalar          |                   | numeric   | 
|              | Additional costs treatment A    | `c_trtA`      | scalar          |                   | numeric   | 
|              | Additional costs treatment B    | `c_trtB`      | scalar          |                   | numeric   | 
|              |                                 |               |                 |                   |           |
|       | **Utility weights**                    |               |                 |                   |           |
|              |  Healthy individuals            | `u_H`         | scalar          |                   | numeric   |
|              |  Sick individuals in Sick       | `u_S1`        | scalar          |                   | numeric   |
|              |  Sick individuals in Sicker     | `u_S2`        | scalar          |                   | numeric   |
|              |  Dead individuals               | `u_D`         | scalar          |                   | numeric   | 
|              |  Treated with treatment A       | `u_trtA`      | scalar          |                   | numeric   | 
|              |                                 |               |                 |                   |           |
|       |  **Outcome structures**           |              |                 |                   |             |  
|  \(\mathbf{A}\)  | Transition dynamics array   |`a_A`          | array           | `n_states` x `n_states` x (`n_t` + 1)  | numeric |
|              | Expected QALYs per cycle under a strategy      | `v_qaly`       |  vector        | 1 x (`n_t` + 1)          | numeric|
|              | Expected costs per cycle under a strategy      | `v_cost`       |  vector        | 1 x (`n_t` + 1)    | numeric   |
|              | Total expected discounted QALYs for a strategy | `n_tot_qaly`   |  scalar        |             | numeric   |
|              | Total expected discounted costs for a strategy | `n_tot_cost`   |  scalar        |            | numeric   |
|              | Summary of the model outcomes   | `df_cea`       | data frame     |                    |           |
|              | Summary of the model outcomes   | `table_cea`    | table          |                    |           |

### Table II: Input parameters for probabilistic analysis  
| Parameter              | Distribution         | Distribution values      | Parameter mean       | Parameter standard error|
|------------------------|----------------------|--------------------------|----------------------|---------|
| Number of simulation   | `n_sim`              | 1000                     |                      |         |
| - Constant rate of dying when Healthy (all-cause mortality)             |$Lognormal$ | $log(\mu)$ = $log(0.002)$   ,  $log(\sigma)$ = 0.01    | 0.002 |   0.00002|
| Annual transition probabilities |                         |                          |                      |         |
| - Disease onset (Healthy to Sick)                         |$Beta$ | \(\alpha\) = 30, \(\beta\) = 170       | 0.15 |   0.026 |
| - Recovery (Sick to Healthy)                              |$Beta$ | \(\alpha\) = 60, \(\beta\) = 60        | 0.5   |   0.045 |
| - Disease progression (Sick to Sicker) in the age-dependent model |$Beta$      | \(\alpha\) = 84, \(\beta\) = 716    | 0.106|   0.011  |
| Risks of disease and treatment  |             |                          |                      |         |
| - Hazard ratio of death in Sick vs Healthy                |$Lognormal$ | $log(\mu)$ = $log(3)$   ,  $log(\sigma)$ = 0.01      | 3    |   0.03  |
| - Hazard ratio of death in Sicker vs Healthy              |$Lognormal$ | $log(\mu)$ = $log(10)$  ,  $log(\sigma)$ = 0.2       | 10   |   0.2     |
| - Hazard ratio of Sick to Sicker under treatment B        |$Lognormal$ | $log(\mu)$ = $log(0.6)$  , $log(\sigma)$ = 0.2       |  0.60 |   0.013   |
| Annual costs                                               |            |                                    |      |         |
| - Healthy individuals                                      |$Gamma$     | $Shape$ = 100  , $Scale$ = 20      | 2000 |   200   |
| - Sick individuals in Sick                                 |$Gamma$     | $Shape$ = 177.8, $Scale$ = 22.5    | 4000 |   300   |
| - Sick individuals in Sicker                               |$Gamma$     | $Shape$ = 225  , $Scale$ = 66.7    | 15000|   1000  |
| - Cost of treatment A for individuals in Sick or Sicker    |$Gamma$     | $Shape$ = 73.5, $Scale$ = 163.3    | 12000|   1400  |
| - Cost of treatment B for individuals in Sick or Sicker    |$Gamma$     | $Shape$ = 86.2, $Scale$ = 150.8    | 13050|   1430  |
| Utility weights                                            |            |                                    |      |         |
| - Healthy individuals                                      |$Beta$      | \(\alpha\) = 200, \(\beta\) = 3    | 0.985|   0.008 |
| - Sick individuals in Sick                                 |$Beta$      | \(\alpha\) = 130, \(\beta\) = 45   | 0.74 |   0.033 |
| - Sick individuals in Sicker                               |$Beta$      | \(\alpha\) = 230, \(\beta\) = 230  | 0.5  |   0.023 |
| - Individuals treated with treatment A                     |$Beta$      | \(\alpha\) = 300, \(\beta\) = 15   | 0.95 |   0.012 |

